Schedule implement
oleh-satoshi/RedPandaBank pull request #1
Opened 2023-01-20 08:15 UTC by oleh-satoshi

2023-01-23 10:42 UTC, Sofasmile requested changes
- ПР мають бути не великими. На роботі ідеальний ПР має бути на 2-3 змінених файла
- скрізь варто підчистити код (видалити коментований код, додати модифікатори, перевірити неймінг)
- весь код не перевіряла, переглянула основне. Пофікси спочатку це, а потім зроблю повторне рев'ю. Бо багато всього зміниться після перших правок

2023-01-23 10:42 UTC, Sofasmile commented on pom.xml
> +<!--        </dependency>-->
прибрати закоментований код

2023-01-23 10:42 UTC, Sofasmile commented on pom.xml
> +<!--        </dependency>-->
видалити

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/config/BeanConfig.java
> +@Component
клас в якому створємо бін має бути відмічений анотацією Configuration
і в цілому цей бін десь використовується?

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/strategy/inlineStrategy/scheduleInline/InlineSaveTeacherName.java
> +//public class InlineSaveTeacherName implements InlineHandler<Update> {
видалити

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/enums/Command.java
> +    SCHEDULE_2("/schedule"),
команди мають бути англійською, і бажано без пробілів

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/enums/WeekDay.java
> +        ALL_WEEK("Вся неделя");
краще мати дні ангдійською, а з БД тягнути переклад цих днів потрібною мовою. Тоді це легше масштабувати. Можна мати підтримку різних мов

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/enums/WeekDay.java
> +    }
в кінці кожного файлу має бути пуста строка. Додай чекстайл в проект

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/keyboard/keyboardBuilder/InlineKeyboardMarkupBuilder.java
> +    abstract InlineKeyboardMarkup build();
чому це клас, бачу тут лише один метод. Можливо краще зробити інтерфейсом?

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/keyboard/keyboardBuilder/InlineKeyboardMarkupBuilderImpl.java
> +    final List<List<InlineKeyboardButton>> keyboard;
модифікатори доступу?

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/keyboard/keyboardBuilder/ReplyKeyboardMarkupBuilderImpl.java
> +    public ReplyKeyboardMarkupBuilderImpl button(String text) {
```suggestion
    public ReplyKeyboardMarkupBuilderImpl addButton(String text) {
```
всі методи повинні починатись з дієслова

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/model/Lesson.java
> +    Long lessonId;
можливо краще прото id? + варто додати скрізь модифікатори

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/model/LessonSchedule.java
> +    Long LessonScheduleId;
назви полів мають бути з маленької

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/service/ChildServiceImpl.java
> +        return null;
nullне варто повертати з методу, краще Optional

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/service/LessonServiceImpl.java
> +        new MessageSenderImpl().sendMessageViaURL(childId,  EmojiParser.parseToUnicode(":calendar: " + "<b>" + day + "</b>"));
в спрінгу ми не повинні створювати об'єкти класів через new

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/service/MessageSenderImpl.java
> +@Scope(value = "prototype")
чому prototype? нам треба мати багато об'єктів цього класу?

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/service/TelegramBot.java
> +    final InlineAddSpecificEventStartTimeButton addSpecificEventStartTimeButton;
дуже багато залежностей. Варто подумати над тим щоб розбити цей клас на кілька окремих

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/service/TelegramBot.java
>      public BotApiMethod<?> onWebhookUpdateReceived(Update update) {
логіку цього методу треба виносити в окремі хендлери. 
можеш створити інтерфейс: 
```
interface CommandHandler {
    void handle(Update update); // буде виконувати основну логіку

    isApplicable(Update update); // цей метод буде перевіряти який хендлер має відпрацьовувати
```
а тоді в класі TelegramBot мати наступне:
```
class TelegramBot {
@Autowired // але краще через конструктор
private List<CommandHandler> handlers;

public BotApiMethod<?> onWebhookUpdateReceived(Update update) {
    CommandHandler correctHandler = handlers.stream()
        .filter(handler -> handler.isApplicable(update)
        .findFirst()
        .orElseThrow();
    correctHandler.handle(update);
}
```

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/strategy/commandStrategy/handler/StartCommandHandler.java
> +                    + "В детстве мне всегда нравилось мирить моих сестричек и братьев друг с другом, "
ці всі тексти краще виносити в БД, а на рівні коду оперувати слагами. Слаг - це ключ, за яким з БД можна діставати ці тексти.
Стуктура БД буде мати вигляд:
- table: translates
- columns: id, slug(UNIQE), value (your text), language (UK, EN...)

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/strategy/commandStrategy/handler/StartCommandHandler.java
> +        } else {
```suggestion
            return sendMessage;
        }
```

2023-01-23 10:42 UTC, Sofasmile commented on src/main/java/com/example/redpandabank/strategy/commandStrategy/handler/scheduleCommand/DeleteEventCommandHandler.java
> +@PackagePrivate
для чого використовуєш анотацію PackagePrivate?

2023-01-30 06:52 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/config/BeanConfig.java
> +@Component
Когда то чтото ругалось, я добавил, щас проверил, а оно уже не надо..

2023-01-31 01:56 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/enums/Command.java
> +    SCHEDULE_2("/schedule"),
Для русской и украинской версии не получиться сделать на английском все команды,  есть reply кнопка и ее отображение это сама команда которая будет отправлена на сервер и без пробелов кнопки выглядят не по юзер френдли, а на inline это пофиксю.

2023-01-31 04:31 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/keyboard/keyboardBuilder/InlineKeyboardMarkupBuilder.java
> +    abstract InlineKeyboardMarkup build();
да, отличная идея!

2023-01-31 04:34 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/model/Lesson.java
> +    Long lessonId;
Я добавлял модификаторы через ломбок, но добавляя @PackagePrivate верил что добавляю private модификатор, уже пофиксил

2023-01-31 04:44 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/model/Lesson.java
> +    Long lessonId;
Начал менять на просто id и там нужно разобраться что оно просит, взял на заметку

2023-01-31 04:49 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/model/LessonSchedule.java
> +    Long LessonScheduleId;
опечатка

2023-01-31 04:57 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/service/LessonServiceImpl.java
> +        new MessageSenderImpl().sendMessageViaURL(childId,  EmojiParser.parseToUnicode(":calendar: " + "<b>" + day + "</b>"));
даа, этот класс создан для работы с отправкой данных в чат, почему когда я работал с объектами этого класса как с бинами, возникала ошибка, если два раза вызывал метод на бине но с разными данными, мне в чат прилетало два одинаковых сообщения, приходили данные из первого вызова метода, я начал играться со скоупами, но это не помогло, я не разрешил проблему и продолжил писать код

2023-01-31 04:58 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/service/MessageSenderImpl.java
> +@Scope(value = "prototype")
это была попытка решить проблему для класса MessageSenderImpl

2023-01-31 04:59 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/service/TelegramBot.java
> +    final InlineAddSpecificEventStartTimeButton addSpecificEventStartTimeButton;
да, уже сделал

2023-01-31 05:01 UTC, oleh-satoshi commented on src/main/java/com/example/redpandabank/strategy/commandStrategy/handler/scheduleCommand/DeleteEventCommandHandler.java
> +@PackagePrivate
Думал аннотация сетит private модификатор..

2023-02-24 09:02 UTC, merged